alipay:
  #网关
  url: https://openapi.alipay.com/gateway.do
  #appid
  appid: 2088831769455774
  #私钥
  private_key: 111
  #请求方式
  format: json
  #编码格式
  charset: utf-8
  #公钥
  public_key: 2222
  #签名方式
  sign_type: RSA2