#加密秘钥版本号
key-version: AES.1
#调用地址
api-url: https://payapi.imipay.com
#敏感信息加密秘钥
key: DhkBuSzwoA2gwusyl4LdsQ==
#环讯平台分配的应用id
up-appid: 7133020439161736211
#签名秘钥
app-secret: V6jLaak932pBK7CxtQJQ4IREi3M5LZqB
#机构应用id
inst-id: '027011'
#版本号
version: 1.0.0

#调用路径
api_route:
  #商户入网类接口
  mcht:
    #商户图片上传
    upload_img: /mcht/upload_img
    #商户信息入网
    create_org_mcht: /mcht/create_org_mcht
    #商户入网信息查询
    query_mcht: /mcht/query_mcht
    #商户开通产品
    add_product: /mcht/add_product
    #修改商户开通产品签约费率
    update_product: /mcht/update_product_model
    #修改商户入网信息
    update_org_mcht: /mcht/update_org_mcht
    #修改商户状态
    update_mcht_staus: /mcht/update_mcht_status
    #修改商户开通产品签约费率
    update_product_model: /mcht/update_product_model
    #修改商户结算银行卡信息
    update_mcht_acct: /mcht/update_mcht_acct
    #查询商户审核状态
    query_mcht_audit: /mcht/query_mcht_audit
  mcht_report:
    #查询无卡商户报备状态
    query_register: /mcht/query/register
    #微信子商户配置
    config_echat_submcht: /mcht/config/wechat/submcht
    #查询微信子商户配置
    config_echat_submcht_query: /mcht/config/wechat/submcht/query
    #查询商户银联信息
    query_unionpay: /mcht/query/unionpay
  pay:
    #扫码支付
    online_trade: /online/trade
    #订单查询
    online_query: /online/query